---
- name: Clean docker
  block:
    - name: Tasks to check and remove stray containers
      include_tasks: remove_stray_containers.yml
  rescue:
    - name: Tasks to stop OS services
      include_tasks: stop_os_services.yml
    - name: Tasks to start OS services
      include_tasks: start_os_services.yml
    - name: Tasks to check and remove stray containers
      include_tasks: remove_stray_containers.yml
