---
- name: Tasks to get serviced mounts
  include_tasks: get_active_volumes.yml

- name: Lazy unmount active volumes
  command:
    cmd: umount -f -l "{{ item }}"
  with_items: active_volumes

- name: Restart NFS service
  service:
    name: nfs
    state: restarted
