---
- name: Clean mounts
  block:
    - name: Tasks to check for mounts
      include_tasks: check_mounts.yml
  rescue:
    - name: Remove serviced volume mounts
      block:
        - name: Tasks to standard remove
          include_tasks: remove_mounts.yml
        - name: Tasks to check for mounts
          include_tasks: check_mounts.yml
      rescue:
        - name: Tasks to lazy remove
          include_tasks: lazy_remove_mounts.yml
